-- Replace APPLY_FUNCTION_APP_NAME before executing as a Microsoft Entra SQL administrator.
CREATE USER [APPLY_FUNCTION_APP_NAME] FROM EXTERNAL PROVIDER;
ALTER ROLE db_datareader ADD MEMBER [APPLY_FUNCTION_APP_NAME];
ALTER ROLE db_datawriter ADD MEMBER [APPLY_FUNCTION_APP_NAME];
GRANT EXECUTE TO [APPLY_FUNCTION_APP_NAME];
